from typing import List, Optional
from datetime import datetime
from uuid import uuid4
from sqlmodel import Field, Relationship, SQLModel


# Define User first, as other models reference it
class User(SQLModel, table=True):
    __tablename__ = "users"
    id: Optional[str] = Field(default=None, primary_key=True, index=True)
    email: str = Field(index=True, unique=True)
    name: str
    picture: Optional[str] = None

    guided_journals: List["GuidedJournal"] = Relationship(back_populates="user")
    free_journals: List["FreeJournal"] = Relationship(back_populates="user")
    gardens: List["Garden"] = Relationship(back_populates="user")
    hints: List["Hint"] = Relationship(back_populates="user")


class FreeJournal(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    user_id: str = Field(foreign_key="users.id", index=True)
    session_id: str = Field(index=True)
    content: str = ""
    created_at: datetime = Field(default_factory=datetime.utcnow)

    user: User = Relationship(back_populates="free_journals")


class GuidedJournal(SQLModel, table=True):
    id: Optional[str] = Field(default_factory=lambda: str(uuid4()), primary_key=True)
    user_id: str = Field(foreign_key="users.id")
    topic: str
    created_at: datetime = Field(default_factory=datetime.utcnow, nullable=False)

    prompts: List["Prompt"] = Relationship(back_populates="guided_journal")
    entries: List["GuidedJournalEntry"] = Relationship(back_populates="guided_journal")
    user: User = Relationship(back_populates="guided_journals")


class Prompt(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    text: str
    guided_journal_id: Optional[str] = Field(default=None, foreign_key="guidedjournal.id")
    guided_journal: Optional[GuidedJournal] = Relationship(back_populates="prompts")
    guided_journal_entry: Optional["GuidedJournalEntry"] = Relationship(back_populates="prompt")


class GuidedJournalEntry(SQLModel, table=True):
    id: Optional[str] = Field(default_factory=lambda: str(uuid4()), primary_key=True)
    guided_journal_id: Optional[str] = Field(default=None, foreign_key="guidedjournal.id")
    prompt_id: Optional[int] = Field(default=None, foreign_key="prompt.id")
    response: str
    created_at: datetime = Field(default_factory=datetime.utcnow, nullable=False)

    guided_journal: Optional[GuidedJournal] = Relationship(back_populates="entries")
    prompt: Optional[Prompt] = Relationship(back_populates="guided_journal_entry")


class Garden(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    user_id: str = Field(foreign_key="users.id", index=True)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    mood: str
    note: Optional[str] = None
    flower_type: str

    user: User = Relationship(back_populates="gardens")


class Hint(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    user_id: str = Field(foreign_key="users.id", index=True)
    session_id: str = Field(index=True)
    hint_text: str
    created_at: datetime = Field(default_factory=datetime.utcnow)

    user: User = Relationship(back_populates="hints")


# Add these Pydantic models for API requests (from GuidedJournal)
class GuidedJournalCreate(SQLModel):
    topic: str
    # prompts will be generated by AI, not provided by user

class GuidedJournalUpdate(SQLModel):
    topic: Optional[str] = None

# No need for model_rebuild() calls here, as all models are defined.
# If there are any remaining forward references, they will be handled by SQLModel/Pydantic automatically.
